Repository Munhak-Zip/Munhak.Zip_Back, pull requests merged in 2024-05, with the labels that each got.

#15 [fix/#9] 머지 수정하기
  .idea/misc.xml
Labels: fix, 다윤

#27 [Add/#26]UserDao구현
  src/main/java/com/example/jpetstore/controller/UserController.java
  src/main/java/com/example/jpetstore/dao/UserDao.java
  src/main/java/com/example/jpetstore/dao/mybatis/MybatisUserDao.java
  src/main/java/com/example/jpetstore/dao/mybatis/mapper/UserMapper.java
  src/main/java/com/example/jpetstore/domain/Interest.java
  src/main/java/com/example/jpetstore/domain/User.java
  src/main/java/com/example/jpetstore/service/UserService.java
  src/main/java/com/example/jpetstore/service/UserServiceImpl.java
  src/main/resources/com/example/jpetstore/dao/mybatis/mapper/UserMapper.xml
  src/test/java/com/example/jpetstore/test/UserTest.java
  target/classes/com/example/jpetstore/controller/UserController.class
  target/classes/com/example/jpetstore/dao/UserDao.class
  target/classes/com/example/jpetstore/dao/mybatis/MybatisUserDao.class
  target/classes/com/example/jpetstore/dao/mybatis/mapper/UserMapper.class
  target/classes/com/example/jpetstore/dao/mybatis/mapper/UserMapper.xml
  target/classes/com/example/jpetstore/domain/Interest.class
  target/classes/com/example/jpetstore/domain/User.class
  target/classes/com/example/jpetstore/service/UserService.class
  target/classes/com/example/jpetstore/service/UserServiceImpl.class
  target/test-classes/com/example/jpetstore/test/UserTest.class
Labels: feat, PULL REQUEST, 다윤

#28 [add/#14] WishDao 에서 deleteWishReview 구현
  .idea/misc.xml
  src/main/java/com/example/jpetstore/dao/WishDao.java
  src/main/java/com/example/jpetstore/dao/mybatis/MybatisWishDao.java
  src/main/java/com/example/jpetstore/dao/mybatis/mapper/WishMapper.java
  src/main/java/com/example/jpetstore/domain/Review.java
  src/main/resources/com/example/jpetstore/dao/mybatis/mapper/WishMapper.xml
  src/test/java/com/example/jpetstore/test/WishTest.java
  target/classes/com/example/jpetstore/dao/SearchDao.class
  target/classes/com/example/jpetstore/dao/WishDao.class
  target/classes/com/example/jpetstore/dao/mybatis/MybatisMovieDao.class
  target/classes/com/example/jpetstore/dao/mybatis/MybatisSearchMovieDao.class
  target/classes/com/example/jpetstore/dao/mybatis/MybatisWishDao.class
  target/classes/com/example/jpetstore/dao/mybatis/mapper/AccountMapper.xml
  target/classes/com/example/jpetstore/dao/mybatis/mapper/SearchMovieMapper.class
  target/classes/com/example/jpetstore/dao/mybatis/mapper/SearchmovieMapper.xml
  target/classes/com/example/jpetstore/dao/mybatis/mapper/WishMapper.class
  target/classes/com/example/jpetstore/dao/mybatis/mapper/WishMapper.xml
  target/classes/com/example/jpetstore/domain/Movie.class
  target/classes/com/example/jpetstore/domain/Review.class
  target/classes/com/example/jpetstore/service/SearchMoviesService.class
  target/classes/dataAccessContext-mybatis.xml
  target/test-classes/com/example/jpetstore/test/MypageTest.class
  target/test-classes/com/example/jpetstore/test/SearchTest.class
  target/test-classes/com/example/jpetstore/test/WishTest.class
Labels: add, PULL REQUEST, test, 미현
